version: "3"
services:
    # app:
    #      build: .
    #      image: haylee-go-app
    #      ports:
    #        - "3000:3000"
    #      volumes:
    #        - .:/usr/src/app

    db:
      image: postgres:9.6-alpine
      volumes: # load in the starter dataset (if any)
             - ./data:/docker-entrypoint-initdb.d
      environment:
             - POSTGRES_USER=haylee
             - POSTGRES_PASSWORD=haylee
             - PGPASSWORD=haylee # for command-line tools
      ports:
             - "5430:5432"

# db connection string will be:
# postgresql://haylee:haylee@localhost:5430
